# language: python - "3.7"

branches:
  only:
    - master

before_install:
    - sudo apt-get update
install:
    # sphinx
    - ls /var/cache/apt/archives/
    - sudo apt-get install python3-pip python3-setuptools python3-wheel #python3-sphinx
    - pip3 install sphinx travis-sphinx recommonmark sphinx_rtd_theme
    # latex pdf
    - sudo apt-get install texlive-full
    - ls /var/cache/apt/archives/
script:
    # 生成 md格式文档
    - python backup/sphinx/gen_source_del_header.py

    # 构建 pdf文档：build/latex/sphinx.pdf
    - python backup/sphinx/gen_source_pdf.py
    - cd backup/sphinx
    - make latexpdf
    - ls 
    - ls build
    - ls build/latex/
    - cp build/latex/leetcodecrowdsource.pdf ../../LeetCodeCrowdsource.pdf
    - cd ../../
    - ls
    
    # 构建 html文档：doc/build
    - python backup/sphinx/gen_source_html.py
    - travis-sphinx build --source=./backup/sphinx/source --nowarn
    - cp ./LeetCodeCrowdsource.pdf doc/build/

after_success:
    - travis-sphinx deploy -b master -c "leetcode.xuezhisd.top" -m "update blog automatically by travis."
