# language: python - "3.7"

branches:
  only:
    - master

# before_install:
    # - sudo apt-get update
install:
    # sphinx
    - sudo apt-get install python3-pip python3-setuptools python3-wheel python3-sphinx
    - pip3 install travis-sphinx recommonmark sphinx_rtd_theme
    # latex pdf
    - sudo apt-get install texlive-full
script:
    # 生成 md格式文档
    - python backup/sphinx/gen_source_md.py

    # 构建 pdf文档：build/latex/sphinx.pdf
    - cd backup/sphinx
    - make latexpdf
    - ls 
    - ls build
    - ls build/latex/
    - cp build/latex/sphinx.pdf ../../LeetCodeCrowdsource.pdf
    - cd ../../
    - ls
    
    # 构建 html文档：doc/build
    - travis-sphinx build --source=./backup/sphinx/source --nowarn
    - cp ./LeetCodeCrowdsource.pdf doc/build/

after_success:
    - travis-sphinx deploy -b master -c "leetcode.xuezhisd.top" -m "update blog automatically by travis."